_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 76
            "2":
                - 1
                - 5
                - 53
                - 55
                - 76
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
batch_size:
    value: 32
classifier:
    value: DGCNN
device:
    value: cuda
epochs:
    value: 500
hidden_feats:
    value: 64
in_feats:
    value: 16
model:
    value: DGCNN
out_feats:
    value: 10
